using System.Globalization;
using System.IO;
using System.Text;
using ConferenciaNFs.Infrastructure;
using ConferenciaNFs.Models;
using CsvHelper;
using CsvHelper.Configuration;
using Dapper;
using Npgsql;

namespace ConferenciaNFs.Data;

public sealed class NotaFiscalRepository
{
    private const int LinhasMetadados = 7;

    private readonly string _connectionString;

    public NotaFiscalRepository(string connectionString)
    {
        if (string.IsNullOrWhiteSpace(connectionString))
            throw new InvalidOperationException(
                "ConnectionString do PostgreSQL nao configurada. Edite app-settings.json na pasta do aplicativo.");

        _connectionString = connectionString.Trim();
        InicializarBanco();
    }

    public string ConnectionString => _connectionString;

    public void TestarConexao()
    {
        using var connection = CriarConexao();
        connection.Open();
        connection.ExecuteScalar<int>("SELECT 1");
    }

    private void InicializarBanco()
    {
        using var connection = CriarConexao();
        connection.Open();

        connection.Execute("""
            CREATE TABLE IF NOT EXISTS NotasFiscais (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ApelidoLoja TEXT NOT NULL,
                NumNota TEXT NOT NULL,
                NomeForn TEXT,
                CnpjForn TEXT,
                ValorNota NUMERIC(18,2) NOT NULL DEFAULT 0,
                DataCompra TEXT,
                DataEmissao TEXT NOT NULL DEFAULT '',
                DiaConferencia TEXT NOT NULL DEFAULT '',
                Observacao TEXT NOT NULL DEFAULT '',
                ChaveUnica TEXT NOT NULL UNIQUE,
                StatusConferencia TEXT NOT NULL DEFAULT 'Pendente'
            );

            CREATE INDEX IF NOT EXISTS IX_NotasFiscais_ApelidoLoja
                ON NotasFiscais (ApelidoLoja);

            CREATE INDEX IF NOT EXISTS IX_NotasFiscais_StatusConferencia
                ON NotasFiscais (StatusConferencia);

            CREATE INDEX IF NOT EXISTS IX_NotasFiscais_DataCompra
                ON NotasFiscais (DataCompra);

            CREATE INDEX IF NOT EXISTS IX_NotasFiscais_DiaConferencia
                ON NotasFiscais (DiaConferencia);

            CREATE INDEX IF NOT EXISTS IX_NotasFiscais_NumNota
                ON NotasFiscais (NumNota);
            """);

        NormalizarApelidosExistentes(connection);
        InicializarTabelaLojaOrdem(connection);
        InicializarTabelaDistribuidoras(connection);
        InicializarTabelaAppConfig(connection);
        InicializarTabelaDevolucoes(connection);
    }

    private const string ConfigDevolucoesDataMinima = "DevolucoesDataMinima";

    private const string SqlJoinDistribuidoraPorCnpj = """
        LEFT JOIN Distribuidoras dist ON regexp_replace(COALESCE(dist.CnpjForn, ''), '[^0-9]', '', 'g')
            = regexp_replace(COALESCE(n.CnpjForn, ''), '[^0-9]', '', 'g')
            AND regexp_replace(COALESCE(n.CnpjForn, ''), '[^0-9]', '', 'g') <> ''
        """;

    private static void InicializarTabelaAppConfig(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS AppConfig (
                Chave TEXT PRIMARY KEY,
                Valor TEXT NOT NULL DEFAULT ''
            );
            """);
    }

    private static void InicializarTabelaDevolucoes(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS Devolucoes (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NotaFiscalId BIGINT NOT NULL UNIQUE,
                StatusDevolucao TEXT NOT NULL DEFAULT 'Pendente',
                DataMarcada TEXT NOT NULL DEFAULT '',
                DataConclusao TEXT NULL,
                Observacao TEXT NOT NULL DEFAULT ''
            );

            CREATE INDEX IF NOT EXISTS IX_Devolucoes_StatusDevolucao
                ON Devolucoes (StatusDevolucao);

            CREATE INDEX IF NOT EXISTS IX_Devolucoes_NotaFiscalId
                ON Devolucoes (NotaFiscalId);
            """);

        // Notas Vermelho entram na fila se ainda nao tiverem registro (respeita data minima por emissao).
        connection.Execute($"""
            INSERT INTO Devolucoes (NotaFiscalId, StatusDevolucao, DataMarcada, Observacao)
            SELECT
                n.Id,
                'Pendente',
                COALESCE(NULLIF(TRIM(n.DiaConferencia), ''), to_char(CURRENT_DATE, 'DD/MM/YYYY')),
                ''
            FROM NotasFiscais n
            LEFT JOIN Devolucoes d ON d.NotaFiscalId = n.Id
            LEFT JOIN AppConfig cfg ON cfg.Chave = '{ConfigDevolucoesDataMinima}'
            WHERE n.StatusConferencia = 'Vermelho'
              AND d.Id IS NULL
              AND (
                cfg.Valor IS NULL OR TRIM(cfg.Valor) = ''
                OR (
                    NULLIF(TRIM(n.DataEmissao), '') IS NOT NULL
                    AND to_date(NULLIF(TRIM(n.DataEmissao), ''), 'DD/MM/YYYY')
                        >= to_date(NULLIF(TRIM(cfg.Valor), ''), 'DD/MM/YYYY')
                )
              );
            """);
    }

    private static void InicializarTabelaDistribuidoras(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS Distribuidoras (
                CnpjForn TEXT PRIMARY KEY,
                NomeForn TEXT NOT NULL DEFAULT '',
                PrazoDevolucaoDias INTEGER NULL,
                RastrearPrazo BOOLEAN NOT NULL DEFAULT FALSE
            );

            CREATE INDEX IF NOT EXISTS IX_Distribuidoras_NomeForn
                ON Distribuidoras (NomeForn);

            CREATE INDEX IF NOT EXISTS IX_Distribuidoras_RastrearPrazo
                ON Distribuidoras (RastrearPrazo);
            """);

        // Popular a partir de notas ja importadas (sem sobrescrever prazo/rastreio).
        connection.Execute("""
            INSERT INTO Distribuidoras (CnpjForn, NomeForn, PrazoDevolucaoDias, RastrearPrazo)
            SELECT DISTINCT ON (TRIM(CnpjForn))
                TRIM(CnpjForn),
                COALESCE(NULLIF(TRIM(NomeForn), ''), TRIM(CnpjForn)),
                NULL,
                FALSE
            FROM NotasFiscais
            WHERE CnpjForn IS NOT NULL AND TRIM(CnpjForn) <> ''
            ORDER BY TRIM(CnpjForn), Id DESC
            ON CONFLICT (CnpjForn) DO UPDATE SET
                NomeForn = EXCLUDED.NomeForn;
            """);

        // Normaliza CNPJs antigos (com mascara) para apenas digitos.
        connection.Execute("""
            UPDATE Distribuidoras
            SET CnpjForn = regexp_replace(COALESCE(CnpjForn, ''), '[^0-9]', '', 'g')
            WHERE CnpjForn ~ '[^0-9]';
            """);
    }

    private static void InicializarTabelaLojaOrdem(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS LojaOrdem (
                ApelidoLoja TEXT PRIMARY KEY,
                NumeroOrdem INTEGER NOT NULL UNIQUE,
                NomeExibicao TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS IX_LojaOrdem_NumeroOrdem
                ON LojaOrdem (NumeroOrdem);
            """);

        AjustarAliasesLojaOrdem(connection);

        foreach (var loja in LojaOrdemSeed.LojasPadrao)
        {
            connection.Execute("""
                INSERT INTO LojaOrdem (ApelidoLoja, NumeroOrdem, NomeExibicao)
                VALUES (@ApelidoLoja, @NumeroOrdem, @NomeExibicao)
                ON CONFLICT (ApelidoLoja) DO NOTHING;
                """, loja);
        }
    }

    private static void NormalizarApelidosExistentes(NpgsqlConnection connection)
    {
        var apelidos = connection.Query<string>("SELECT DISTINCT ApelidoLoja FROM NotasFiscais");
        foreach (var apelidoAtual in apelidos)
        {
            var apelidoNormalizado = LojaAliasNormalizer.Normalizar(apelidoAtual);
            if (apelidoNormalizado == apelidoAtual)
                continue;

            connection.Execute("""
                UPDATE NotasFiscais
                SET ApelidoLoja = @ApelidoNovo
                WHERE ApelidoLoja = @ApelidoAtual
                """, new
            {
                ApelidoAtual = apelidoAtual,
                ApelidoNovo = apelidoNormalizado
            });
        }
    }

    private static void AjustarAliasesLojaOrdem(NpgsqlConnection connection)
    {
        connection.Execute("""
            UPDATE LojaOrdem
            SET ApelidoLoja = 'QUATA FILI', NomeExibicao = 'Quata Filial'
            WHERE ApelidoLoja = 'QUATA FIL';

            UPDATE LojaOrdem
            SET ApelidoLoja = 'MANOEL GOU', NomeExibicao = 'Manoel Goulart'
            WHERE ApelidoLoja = 'MANOEL GO';

            UPDATE LojaOrdem
            SET ApelidoLoja = '__TMP_LUCELIA_CE__'
            WHERE ApelidoLoja = 'LUCELIA CENTRO';

            UPDATE LojaOrdem
            SET ApelidoLoja = 'LUCELIA', NomeExibicao = 'Lucelia'
            WHERE ApelidoLoja = 'LUCELIA CE' AND NumeroOrdem = 20;

            UPDATE LojaOrdem
            SET ApelidoLoja = 'LUCELIA CE', NomeExibicao = 'Lucelia Centro'
            WHERE ApelidoLoja = '__TMP_LUCELIA_CE__';
            """);
    }

    public async Task<int> ImportarCsvAsync(
        string caminhoArquivo,
        string diaConferencia,
        CancellationToken cancellationToken = default)
    {
        if (!File.Exists(caminhoArquivo))
            throw new FileNotFoundException("Arquivo CSV nao encontrado.", caminhoArquivo);

        var dia = diaConferencia.Trim();
        if (string.IsNullOrWhiteSpace(dia))
            throw new ArgumentException("Informe o dia da conferencia para importar o CSV.", nameof(diaConferencia));

        var registros = await LerRegistrosCsvAsync(caminhoArquivo, dia, cancellationToken);
        if (registros.Count == 0)
            return 0;

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);

        var inseridos = 0;

        const string sql = """
            INSERT INTO NotasFiscais (
                ApelidoLoja, NumNota, NomeForn, CnpjForn,
                ValorNota, DataCompra, DataEmissao, DiaConferencia, ChaveUnica, StatusConferencia
            ) VALUES (
                @ApelidoLoja, @NumNota, @NomeForn, @CnpjForn,
                @ValorNota, @DataCompra, @DataEmissao, @DiaConferencia, @ChaveUnica, @StatusConferencia
            )
            ON CONFLICT (ChaveUnica) DO UPDATE SET
                ApelidoLoja = EXCLUDED.ApelidoLoja,
                NomeForn = EXCLUDED.NomeForn,
                ValorNota = EXCLUDED.ValorNota,
                DataCompra = EXCLUDED.DataCompra,
                DiaConferencia = EXCLUDED.DiaConferencia,
                DataEmissao = CASE
                    WHEN EXCLUDED.DataEmissao <> '' THEN EXCLUDED.DataEmissao
                    ELSE NotasFiscais.DataEmissao
                END;
            """;

        const string sqlContarExistente = """
            SELECT 1
            FROM NotasFiscais
            WHERE ChaveUnica = @ChaveUnica
            LIMIT 1
            """;

        foreach (var nota in registros)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var jaExistia = await connection.ExecuteScalarAsync<int?>(
                sqlContarExistente,
                new { nota.ChaveUnica },
                transaction) is not null;

            await connection.ExecuteAsync(sql, nota, transaction);

            if (!jaExistia)
                inseridos++;
        }

        await SincronizarDistribuidorasAsync(connection, registros, transaction, cancellationToken);

        await transaction.CommitAsync(cancellationToken);
        return inseridos;
    }

    private static async Task SincronizarDistribuidorasAsync(
        NpgsqlConnection connection,
        IReadOnlyList<NotaFiscal> registros,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        var porCnpj = registros
            .Where(n => !string.IsNullOrWhiteSpace(n.CnpjForn))
            .GroupBy(n => n.CnpjForn.Trim(), StringComparer.OrdinalIgnoreCase)
            .Select(g => new
            {
                CnpjForn = CnpjNormalizer.Normalizar(g.Key),
                NomeForn = g
                    .Select(n => n.NomeForn?.Trim() ?? string.Empty)
                    .LastOrDefault(n => !string.IsNullOrWhiteSpace(n))
                    ?? CnpjNormalizer.Normalizar(g.Key)
            })
            .Where(x => !string.IsNullOrWhiteSpace(x.CnpjForn));

        const string sql = """
            INSERT INTO Distribuidoras (CnpjForn, NomeForn, PrazoDevolucaoDias, RastrearPrazo)
            VALUES (@CnpjForn, @NomeForn, NULL, FALSE)
            ON CONFLICT (CnpjForn) DO UPDATE SET
                NomeForn = EXCLUDED.NomeForn;
            """;

        foreach (var item in porCnpj)
        {
            cancellationToken.ThrowIfCancellationRequested();
            await connection.ExecuteAsync(sql, item, transaction);
        }
    }

    public async Task<IReadOnlyList<Distribuidora>> ObterDistribuidorasAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<Distribuidora>("""
            SELECT CnpjForn, NomeForn, PrazoDevolucaoDias, RastrearPrazo
            FROM Distribuidoras
            ORDER BY NomeForn, CnpjForn
            """);

        return resultado.ToList();
    }

    public async Task AtualizarDistribuidoraAsync(
        string cnpjForn,
        int? prazoDevolucaoDias,
        bool rastrearPrazo,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(cnpjForn))
            throw new ArgumentException("CNPJ da distribuidora e obrigatorio.", nameof(cnpjForn));

        if (prazoDevolucaoDias is < 0)
            throw new ArgumentOutOfRangeException(nameof(prazoDevolucaoDias), "Prazo nao pode ser negativo.");

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhas =         await connection.ExecuteAsync("""
            UPDATE Distribuidoras
            SET PrazoDevolucaoDias = @PrazoDevolucaoDias,
                RastrearPrazo = @RastrearPrazo
            WHERE regexp_replace(COALESCE(CnpjForn, ''), '[^0-9]', '', 'g') = @CnpjForn
            """, new
        {
            CnpjForn = CnpjNormalizer.Normalizar(cnpjForn),
            PrazoDevolucaoDias = prazoDevolucaoDias,
            RastrearPrazo = rastrearPrazo
        });

        if (linhas == 0)
            throw new InvalidOperationException($"Distribuidora com CNPJ {cnpjForn} nao encontrada.");
    }

    public async Task<IReadOnlyList<string>> ObterDatasDisponiveisAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var datas = await connection.QueryAsync<string>("""
            SELECT DISTINCT DiaConferencia
            FROM NotasFiscais
            WHERE DiaConferencia IS NOT NULL AND TRIM(DiaConferencia) <> ''
            """);

        return datas
            .Where(d => !string.IsNullOrWhiteSpace(d))
            .OrderByDescending(d => d, Comparer<string>.Create(DataCompraParser.Comparar))
            .ToList();
    }

    public async Task<string> ResolverChaveDataCompraAsync(
        DateTime data,
        CancellationToken cancellationToken = default)
    {
        var alvo = data.Date;
        var datas = await ObterDatasDisponiveisAsync(cancellationToken);

        var existente = datas.FirstOrDefault(d =>
            DataCompraParser.TentarConverter(d)?.Date == alvo);

        return existente ?? DataCompraParser.Formatar(alvo);
    }

    public async Task<IReadOnlyList<LojaPendencia>> ObterPendenciasPorLojaAsync(
        string dataCompra,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<LojaPendencia>("""
            SELECT
                n.ApelidoLoja,
                SUM(CASE
                    WHEN n.StatusConferencia IN (@StatusPendente, @StatusAmarelo) THEN 1
                    ELSE 0
                END)::int AS Pendencias,
                COALESCE(MAX(l.NumeroOrdem), 9999) AS NumeroOrdem,
                COALESCE(NULLIF(MAX(l.NomeExibicao), ''), n.ApelidoLoja) AS NomeExibicao
            FROM NotasFiscais n
            LEFT JOIN LojaOrdem l ON l.ApelidoLoja = n.ApelidoLoja
            WHERE n.DiaConferencia = @DiaConferencia
            GROUP BY n.ApelidoLoja
            ORDER BY NumeroOrdem, n.ApelidoLoja
            """, new
        {
            StatusPendente = StatusConferenciaValues.Pendente,
            StatusAmarelo = StatusConferenciaValues.Amarelo,
            DiaConferencia = dataCompra
        });

        return resultado.ToList();
    }

    public async Task<IReadOnlyList<NotaFiscal>> ObterNotasPorLojaAsync(
        string apelidoLoja,
        string dataCompra,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<NotaFiscal>("""
            SELECT *
            FROM NotasFiscais
            WHERE ApelidoLoja = @Loja
              AND DiaConferencia = @DiaConferencia
            """, new { Loja = apelidoLoja, DiaConferencia = dataCompra });

        return resultado
            .OrderBy(n => n, Comparer<NotaFiscal>.Create(CompararNotasConferencia))
            .ToList();
    }

    private static int CompararNotasConferencia(NotaFiscal a, NotaFiscal b)
    {
        var comparacaoData = DataCompraParser.CompararAscendente(a.DataEmissao, b.DataEmissao);
        if (comparacaoData != 0)
            return comparacaoData;

        var comparacaoFornecedor = string.Compare(a.NomeForn, b.NomeForn, StringComparison.OrdinalIgnoreCase);
        if (comparacaoFornecedor != 0)
            return comparacaoFornecedor;

        return string.Compare(a.NumNota, b.NumNota, StringComparison.OrdinalIgnoreCase);
    }

    public async Task<IReadOnlyList<NotaPesquisaResultado>> PesquisarPrimeiraConferenciaPorNumNotaAsync(
        string numNota,
        CancellationToken cancellationToken = default)
    {
        var termo = numNota.Trim();
        if (string.IsNullOrWhiteSpace(termo))
            return [];

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var notas = (await connection.QueryAsync<NotaFiscal>("""
            SELECT *
            FROM NotasFiscais
            WHERE LOWER(TRIM(NumNota)) = LOWER(TRIM(@Termo))
            """, new { Termo = termo })).ToList();

        return notas
            .GroupBy(n => $"{n.NumNota}|{n.CnpjForn}", StringComparer.OrdinalIgnoreCase)
            .Select(grupo =>
            {
                var ordenadas = grupo
                    .OrderBy(n => n, Comparer<NotaFiscal>.Create((a, b) =>
                        DataCompraParser.CompararAscendente(a.DiaConferencia, b.DiaConferencia)))
                    .ToList();

                var primeira = ordenadas[0];
                return new NotaPesquisaResultado
                {
                    NumNota = primeira.NumNota,
                    ApelidoLoja = primeira.ApelidoLoja,
                    NomeForn = primeira.NomeForn,
                    DataPrimeiraConferencia = primeira.DiaConferencia,
                    StatusConferencia = primeira.StatusConferencia,
                    Observacao = primeira.Observacao,
                    OcorrenciasTotais = ordenadas.Count
                };
            })
            .OrderBy(r => r.NomeForn, StringComparer.OrdinalIgnoreCase)
            .ThenBy(r => r.ApelidoLoja, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    public async Task<IReadOnlyList<NotaFiscal>> ObterTodasNotasPorDataAsync(
        string dataCompra,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var notas = (await connection.QueryAsync<NotaFiscal>("""
            SELECT *
            FROM NotasFiscais
            WHERE DiaConferencia = @DiaConferencia
            """, new { DiaConferencia = dataCompra })).ToList();

        var ordens = await connection.QueryAsync<(string ApelidoLoja, int NumeroOrdem)>("""
            SELECT ApelidoLoja, NumeroOrdem
            FROM LojaOrdem
            """);

        var ordemPorLoja = ordens.ToDictionary(o => o.ApelidoLoja, o => o.NumeroOrdem, StringComparer.Ordinal);

        return notas
            .OrderBy(n => ordemPorLoja.TryGetValue(n.ApelidoLoja, out var ordem) ? ordem : 9999)
            .ThenBy(n => n, Comparer<NotaFiscal>.Create(CompararNotasConferencia))
            .ToList();
    }

    public async Task AtualizarStatusConferenciaAsync(
        long id,
        string status,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);

        var statusAtual = await connection.QuerySingleOrDefaultAsync<string>("""
            SELECT StatusConferencia
            FROM NotasFiscais
            WHERE Id = @Id
            """, new { Id = id }, transaction);

        if (statusAtual is null)
            throw new InvalidOperationException($"Nota com Id {id} nao encontrada.");

        await connection.ExecuteAsync("""
            UPDATE NotasFiscais
            SET StatusConferencia = @Status
            WHERE Id = @Id
            """, new { Id = id, Status = status }, transaction);

        if (status == StatusConferenciaValues.Vermelho
            && statusAtual != StatusConferenciaValues.Vermelho)
        {
            var dataMinima = await ObterDataMinimaDevolucoesInternalAsync(connection, transaction);
            if (await NotaEntraNoPeriodoDevolucaoAsync(connection, transaction, id, dataMinima))
                await RegistrarDevolucaoPendenteAsync(connection, transaction, id, cancellationToken);
        }
        else if (status != StatusConferenciaValues.Vermelho
                 && statusAtual == StatusConferenciaValues.Vermelho)
        {
            // So remove pendencias da fila; devolucoes concluidas permanecem no historico.
            await connection.ExecuteAsync("""
                DELETE FROM Devolucoes
                WHERE NotaFiscalId = @NotaFiscalId
                  AND StatusDevolucao = @StatusPendente
                """, new
            {
                NotaFiscalId = id,
                StatusPendente = StatusDevolucaoValues.Pendente
            }, transaction);
        }

        await transaction.CommitAsync(cancellationToken);
    }

    private static async Task<bool> NotaEntraNoPeriodoDevolucaoAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        long notaFiscalId,
        DateTime? dataMinima)
    {
        if (!dataMinima.HasValue)
            return true;

        var dataEmissao = await connection.QuerySingleOrDefaultAsync<string?>("""
            SELECT DataEmissao
            FROM NotasFiscais
            WHERE Id = @Id
            """, new { Id = notaFiscalId }, transaction);

        var emissao = DataCompraParser.TentarConverter(dataEmissao);
        if (!emissao.HasValue)
            return false;

        return emissao.Value.Date >= dataMinima.Value.Date;
    }

    private static bool DevolucaoVisivelNoPeriodo(DevolucaoItem item, DateTime? dataMinima)
    {
        if (item.StatusDevolucao != StatusDevolucaoValues.Pendente)
            return true;

        if (!dataMinima.HasValue)
            return true;

        var emissao = item.DataReferenciaRastreio;
        return emissao.HasValue && emissao.Value.Date >= dataMinima.Value.Date;
    }

    private static async Task RegistrarDevolucaoPendenteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        long notaFiscalId,
        CancellationToken cancellationToken)
    {
        var dataMarcada = DataCompraParser.Formatar(DateTime.Today);
        await connection.ExecuteAsync("""
            INSERT INTO Devolucoes (NotaFiscalId, StatusDevolucao, DataMarcada, DataConclusao, Observacao)
            VALUES (@NotaFiscalId, @StatusDevolucao, @DataMarcada, NULL, '')
            ON CONFLICT (NotaFiscalId) DO UPDATE SET
                StatusDevolucao = EXCLUDED.StatusDevolucao,
                DataMarcada = EXCLUDED.DataMarcada,
                DataConclusao = NULL,
                Observacao = ''
            WHERE Devolucoes.StatusDevolucao = @StatusPendente;
            """, new
        {
            NotaFiscalId = notaFiscalId,
            StatusDevolucao = StatusDevolucaoValues.Pendente,
            StatusPendente = StatusDevolucaoValues.Pendente,
            DataMarcada = dataMarcada
        }, transaction);
    }

    public async Task<IReadOnlyList<DevolucaoItem>> ObterDevolucoesAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<DevolucaoItem>($"""
            SELECT
                d.Id,
                d.NotaFiscalId,
                n.ApelidoLoja,
                n.NumNota,
                n.NomeForn,
                n.CnpjForn,
                n.ValorNota,
                n.DataEmissao,
                n.DiaConferencia,
                d.StatusDevolucao,
                d.DataMarcada,
                d.DataConclusao,
                d.Observacao,
                dist.PrazoDevolucaoDias,
                COALESCE(dist.RastrearPrazo, FALSE) AS RastrearPrazo
            FROM Devolucoes d
            INNER JOIN NotasFiscais n ON n.Id = d.NotaFiscalId
            {SqlJoinDistribuidoraPorCnpj}
            ORDER BY
                CASE d.StatusDevolucao
                    WHEN 'Pendente' THEN 0
                    WHEN 'Devolvida' THEN 1
                    ELSE 2
                END,
                n.DataEmissao,
                n.NomeForn,
                n.NumNota
            """);

        var dataMinima = await ObterDataMinimaDevolucoesInternalAsync(connection, transaction: null);
        var lista = resultado.ToList();
        if (!dataMinima.HasValue)
            return lista;

        return lista
            .Where(d => DevolucaoVisivelNoPeriodo(d, dataMinima))
            .ToList();
    }

    public async Task<DateTime?> ObterDataMinimaDevolucoesAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        return await ObterDataMinimaDevolucoesInternalAsync(connection, transaction: null);
    }

    public async Task SalvarDataMinimaDevolucoesAsync(
        DateTime? dataMinima,
        bool removerPendentesAnteriores,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);

        var valor = dataMinima.HasValue
            ? DataCompraParser.Formatar(dataMinima.Value.Date)
            : string.Empty;

        await connection.ExecuteAsync("""
            INSERT INTO AppConfig (Chave, Valor)
            VALUES (@Chave, @Valor)
            ON CONFLICT (Chave) DO UPDATE SET Valor = EXCLUDED.Valor;
            """, new
        {
            Chave = ConfigDevolucoesDataMinima,
            Valor = valor
        }, transaction);

        if (removerPendentesAnteriores && dataMinima.HasValue)
        {
            var pendentes = (await connection.QueryAsync<DevolucaoItem>($"""
                SELECT
                    d.Id,
                    d.NotaFiscalId,
                    n.ApelidoLoja,
                    n.NumNota,
                    n.NomeForn,
                    n.CnpjForn,
                    n.ValorNota,
                    n.DataEmissao,
                    n.DiaConferencia,
                    d.StatusDevolucao,
                    d.DataMarcada,
                    d.DataConclusao,
                    d.Observacao,
                    dist.PrazoDevolucaoDias,
                    COALESCE(dist.RastrearPrazo, FALSE) AS RastrearPrazo
                FROM Devolucoes d
                INNER JOIN NotasFiscais n ON n.Id = d.NotaFiscalId
                {SqlJoinDistribuidoraPorCnpj}
                WHERE d.StatusDevolucao = @StatusPendente
                """, new { StatusPendente = StatusDevolucaoValues.Pendente }, transaction)).ToList();

            var idsRemover = pendentes
                .Where(d => !DevolucaoVisivelNoPeriodo(d, dataMinima))
                .Select(d => d.Id)
                .ToList();

            if (idsRemover.Count > 0)
            {
                await connection.ExecuteAsync("""
                    DELETE FROM Devolucoes
                    WHERE Id = ANY(@Ids)
                    """, new { Ids = idsRemover.ToArray() }, transaction);
            }
        }

        await transaction.CommitAsync(cancellationToken);
    }

    private static async Task<DateTime?> ObterDataMinimaDevolucoesInternalAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction? transaction)
    {
        var valor = await connection.QuerySingleOrDefaultAsync<string>("""
            SELECT Valor
            FROM AppConfig
            WHERE Chave = @Chave
            """, new { Chave = ConfigDevolucoesDataMinima }, transaction);

        return DataCompraParser.TentarConverter(valor);
    }

    public async Task AtualizarStatusDevolucaoAsync(
        long devolucaoId,
        string statusDevolucao,
        string? observacao,
        CancellationToken cancellationToken = default)
    {
        if (statusDevolucao is not (
            StatusDevolucaoValues.Pendente
            or StatusDevolucaoValues.Devolvida
            or StatusDevolucaoValues.PerdeuPrazo))
        {
            throw new ArgumentException("Status de devolucao invalido.", nameof(statusDevolucao));
        }

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var dataConclusaoNova = statusDevolucao == StatusDevolucaoValues.Pendente
            ? null
            : DataCompraParser.Formatar(DateTime.Today);

        var linhas = await connection.ExecuteAsync("""
            UPDATE Devolucoes
            SET StatusDevolucao = @StatusDevolucao,
                Observacao = @Observacao,
                DataConclusao = CASE
                    WHEN @StatusDevolucao = 'Pendente' THEN NULL
                    WHEN StatusDevolucao <> @StatusDevolucao THEN @DataConclusaoNova
                    WHEN DataConclusao IS NULL OR TRIM(DataConclusao) = '' THEN @DataConclusaoNova
                    ELSE DataConclusao
                END
            WHERE Id = @Id
            """, new
        {
            Id = devolucaoId,
            StatusDevolucao = statusDevolucao,
            Observacao = observacao?.Trim() ?? string.Empty,
            DataConclusaoNova = dataConclusaoNova
        });

        if (linhas == 0)
            throw new InvalidOperationException($"Devolucao com Id {devolucaoId} nao encontrada.");
    }

    public async Task AtualizarObservacaoAsync(
        long id,
        string observacao,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhasAfetadas = await connection.ExecuteAsync("""
            UPDATE NotasFiscais
            SET Observacao = @Observacao
            WHERE Id = @Id
            """, new { Id = id, Observacao = observacao ?? string.Empty });

        if (linhasAfetadas == 0)
            throw new InvalidOperationException($"Nota com Id {id} nao encontrada.");
    }

    public async Task<IReadOnlyList<LojaOrdem>> ObterLojasCadastradasAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<LojaOrdem>("""
            SELECT ApelidoLoja, NumeroOrdem, NomeExibicao
            FROM LojaOrdem
            ORDER BY NumeroOrdem
            """);

        return resultado.ToList();
    }

    public async Task<IReadOnlyList<string>> ObterApelidosSemOrdemAsync(
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var resultado = await connection.QueryAsync<string>("""
            SELECT DISTINCT n.ApelidoLoja
            FROM NotasFiscais n
            LEFT JOIN LojaOrdem l ON l.ApelidoLoja = n.ApelidoLoja
            WHERE l.ApelidoLoja IS NULL
            ORDER BY n.ApelidoLoja
            """);

        return resultado.ToList();
    }

    public async Task SalvarLojaOrdemAsync(LojaOrdem loja, CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var numeroEmUso = await connection.ExecuteScalarAsync<int?>("""
            SELECT NumeroOrdem
            FROM LojaOrdem
            WHERE NumeroOrdem = @NumeroOrdem
              AND ApelidoLoja <> @ApelidoLoja
            LIMIT 1
            """, loja);

        if (numeroEmUso.HasValue)
            throw new InvalidOperationException($"O numero {loja.NumeroOrdem} ja esta em uso por outra loja.");

        await connection.ExecuteAsync("""
            INSERT INTO LojaOrdem (ApelidoLoja, NumeroOrdem, NomeExibicao)
            VALUES (@ApelidoLoja, @NumeroOrdem, @NomeExibicao)
            ON CONFLICT (ApelidoLoja) DO UPDATE SET
                NumeroOrdem = EXCLUDED.NumeroOrdem,
                NomeExibicao = EXCLUDED.NomeExibicao;
            """, loja);
    }

    public async Task RemoverLojaOrdemAsync(string apelidoLoja, CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        await connection.ExecuteAsync("""
            DELETE FROM LojaOrdem WHERE ApelidoLoja = @ApelidoLoja
            """, new { ApelidoLoja = apelidoLoja });
    }

    private static async Task<List<NotaFiscal>> LerRegistrosCsvAsync(
        string caminhoArquivo,
        string diaConferencia,
        CancellationToken cancellationToken)
    {
        var delimitador = CsvDelimitadorDetector.Detectar(caminhoArquivo);

        await using var stream = new FileStream(
            caminhoArquivo,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            bufferSize: 4096,
            useAsync: true);

        using var reader = new StreamReader(stream, Encoding.Latin1, detectEncodingFromByteOrderMarks: true);

        for (var i = 0; i < LinhasMetadados; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (await reader.ReadLineAsync(cancellationToken) is null)
                throw new InvalidDataException("O arquivo CSV nao possui cabecalho apos as linhas de metadados.");
        }

        var csvConfig = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            Delimiter = delimitador.ToString(),
            HasHeaderRecord = true,
            MissingFieldFound = null,
            BadDataFound = null,
            HeaderValidated = null,
            TrimOptions = TrimOptions.Trim,
            PrepareHeaderForMatch = args => args.Header.Trim().ToUpperInvariant()
        };

        using var parser = new CsvParser(reader, csvConfig);
        using var csv = new CsvReader(parser);

        var resultado = new List<NotaFiscal>();

        while (await csv.ReadAsync())
        {
            cancellationToken.ThrowIfCancellationRequested();

            var registro = csv.GetRecord<NotaFiscalCsvRecord>();
            if (registro is null)
                continue;

            var numNota = registro.NumNota.Trim();
            var cnpjForn = CnpjNormalizer.Normalizar(registro.CnpjForn);

            if (string.IsNullOrWhiteSpace(numNota) || string.IsNullOrWhiteSpace(cnpjForn))
                continue;

            resultado.Add(new NotaFiscal
            {
                ApelidoLoja = LojaAliasNormalizer.Normalizar(registro.ApelidoLoja),
                NumNota = numNota,
                NomeForn = registro.NomeForn.Trim(),
                CnpjForn = cnpjForn,
                ValorNota = ValorMonetarioParser.Parse(registro.ValorNota),
                DataCompra = registro.DataCompra.Trim(),
                DataEmissao = registro.DataEmissao.Trim(),
                DiaConferencia = diaConferencia,
                ChaveUnica = NotaFiscal.GerarChaveUnica(
                    LojaAliasNormalizer.Normalizar(registro.ApelidoLoja),
                    numNota,
                    cnpjForn,
                    diaConferencia,
                    registro.DataCompra.Trim()),
                StatusConferencia = StatusConferenciaValues.Pendente
            });
        }

        return resultado;
    }

    private NpgsqlConnection CriarConexao() => new(_connectionString);
}
