using System.Globalization;
using ConferenciaNFs.Infrastructure;
using ConferenciaNFs.Models;
using Dapper;
using Npgsql;

namespace ConferenciaNFs.Data;

public sealed partial class NotaFiscalRepository
{
    private static void InicializarTabelaItensNota(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS ItensNota (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NotaFiscalId BIGINT NOT NULL REFERENCES NotasFiscais(Id) ON DELETE CASCADE,
                CodCompra INTEGER NULL,
                Sequencia INTEGER NOT NULL,
                CodProd INTEGER NOT NULL DEFAULT 0,
                NomeProd TEXT NOT NULL DEFAULT '',
                BarrasEan TEXT NOT NULL DEFAULT '',
                BarrasEanTrib TEXT NOT NULL DEFAULT '',
                QuantItemCompra NUMERIC(18,4) NOT NULL DEFAULT 0,
                ValorItemCompra NUMERIC(18,4) NOT NULL DEFAULT 0,
                Desconto NUMERIC(18,4) NOT NULL DEFAULT 0,
                CustoNota NUMERIC(18,4) NOT NULL DEFAULT 0,
                NumLote TEXT NULL,
                DataValidade TEXT NULL,
                AtualizadoEm TEXT NOT NULL DEFAULT '',
                UNIQUE (NotaFiscalId, Sequencia)
            );

            CREATE INDEX IF NOT EXISTS IX_ItensNota_NotaFiscalId
                ON ItensNota (NotaFiscalId);
            """);
    }

    private static void InicializarTabelaMotivosDevolucao(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS MotivosDevolucao (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Descricao TEXT NOT NULL UNIQUE,
                Ativo BOOLEAN NOT NULL DEFAULT TRUE
            );
            """);

        foreach (var descricao in MotivoDevolucaoSeed.Padrao)
        {
            connection.Execute("""
                INSERT INTO MotivosDevolucao (Descricao, Ativo)
                VALUES (@Descricao, TRUE)
                ON CONFLICT (Descricao) DO NOTHING;
                """, new { Descricao = descricao });
        }
    }

    private static void InicializarTabelaDevolucaoItens(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS DevolucaoItens (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                DevolucaoId BIGINT NOT NULL REFERENCES Devolucoes(Id) ON DELETE CASCADE,
                NotaFiscalId BIGINT NOT NULL,
                Sequencia INTEGER NOT NULL,
                CodProd INTEGER NOT NULL DEFAULT 0,
                NomeProd TEXT NOT NULL DEFAULT '',
                BarrasEan TEXT NOT NULL DEFAULT '',
                Quantidade NUMERIC(18,4) NOT NULL,
                CustoNota NUMERIC(18,4) NOT NULL DEFAULT 0,
                Motivo TEXT NOT NULL,
                Classe TEXT NOT NULL,
                UNIQUE (DevolucaoId, Sequencia)
            );

            CREATE INDEX IF NOT EXISTS IX_DevolucaoItens_DevolucaoId
                ON DevolucaoItens (DevolucaoId);
            """);
    }

    private static void InicializarTabelaDevolucaoObservacoes(NpgsqlConnection connection)
    {
        connection.Execute("""
            CREATE TABLE IF NOT EXISTS DevolucaoObservacoes (
                Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                DevolucaoId BIGINT NOT NULL REFERENCES Devolucoes(Id) ON DELETE CASCADE,
                Texto TEXT NOT NULL,
                CriadaEm TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS IX_DevolucaoObservacoes_DevolucaoId
                ON DevolucaoObservacoes (DevolucaoId);
            """);

        connection.Execute("""
            INSERT INTO DevolucaoObservacoes (DevolucaoId, Texto, CriadaEm)
            SELECT
                d.Id,
                TRIM(d.Observacao),
                COALESCE(NULLIF(TRIM(d.DataMarcada), ''), to_char(CURRENT_TIMESTAMP, 'DD/MM/YYYY HH24:MI'))
            FROM Devolucoes d
            WHERE TRIM(COALESCE(d.Observacao, '')) <> ''
              AND NOT EXISTS (
                    SELECT 1
                    FROM DevolucaoObservacoes o
                    WHERE o.DevolucaoId = d.Id
              );
            """);
    }

    public async Task SubstituirItensNotaAsync(
        long notaFiscalId,
        IReadOnlyList<ItemNotaSnapshot> itens,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var tx = await connection.BeginTransactionAsync(cancellationToken);

        await connection.ExecuteAsync(new CommandDefinition(
            "DELETE FROM ItensNota WHERE NotaFiscalId = @NotaFiscalId",
            new { NotaFiscalId = notaFiscalId },
            tx,
            cancellationToken: cancellationToken));

        var agora = DateTime.Now.ToString("dd/MM/yyyy HH:mm", CultureInfo.GetCultureInfo("pt-BR"));
        foreach (var item in itens)
        {
            await connection.ExecuteAsync(new CommandDefinition(
                """
                INSERT INTO ItensNota (
                    NotaFiscalId, CodCompra, Sequencia, CodProd, NomeProd,
                    BarrasEan, BarrasEanTrib, QuantItemCompra, ValorItemCompra,
                    Desconto, CustoNota, NumLote, DataValidade, AtualizadoEm)
                VALUES (
                    @NotaFiscalId, @CodCompra, @Sequencia, @CodProd, @NomeProd,
                    @BarrasEan, @BarrasEanTrib, @QuantItemCompra, @ValorItemCompra,
                    @Desconto, @CustoNota, @NumLote, @DataValidade, @AtualizadoEm)
                """,
                new
                {
                    item.NotaFiscalId,
                    item.CodCompra,
                    item.Sequencia,
                    item.CodProd,
                    item.NomeProd,
                    item.BarrasEan,
                    item.BarrasEanTrib,
                    item.QuantItemCompra,
                    item.ValorItemCompra,
                    item.Desconto,
                    item.CustoNota,
                    item.NumLote,
                    item.DataValidade,
                    AtualizadoEm = agora
                },
                tx,
                cancellationToken: cancellationToken));
        }

        await tx.CommitAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<ItemNotaSnapshot>> ObterItensNotaAsync(
        long notaFiscalId,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhas = await connection.QueryAsync<ItemNotaSnapshot>(new CommandDefinition(
            """
            SELECT
                Id, NotaFiscalId, CodCompra, Sequencia, CodProd, NomeProd,
                BarrasEan, BarrasEanTrib, QuantItemCompra, ValorItemCompra,
                Desconto, CustoNota, NumLote, DataValidade, AtualizadoEm
            FROM ItensNota
            WHERE NotaFiscalId = @NotaFiscalId
            ORDER BY Sequencia
            """,
            new { NotaFiscalId = notaFiscalId },
            cancellationToken: cancellationToken));

        return linhas.AsList();
    }

    public async Task<IReadOnlyList<MotivoDevolucao>> ListarMotivosDevolucaoAsync(
        bool somenteAtivos,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var sql = somenteAtivos
            ? "SELECT Id, Descricao, Ativo FROM MotivosDevolucao WHERE Ativo = TRUE ORDER BY Descricao"
            : "SELECT Id, Descricao, Ativo FROM MotivosDevolucao ORDER BY Ativo DESC, Descricao";

        var linhas = await connection.QueryAsync<MotivoDevolucao>(new CommandDefinition(
            sql,
            cancellationToken: cancellationToken));
        return linhas.AsList();
    }

    public async Task SalvarMotivoDevolucaoAsync(
        string descricao,
        CancellationToken cancellationToken = default)
    {
        var texto = (descricao ?? string.Empty).Trim();
        if (texto.Length < 3)
            throw new InvalidOperationException("Informe um motivo com pelo menos 3 caracteres.");

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var existente = await connection.QuerySingleOrDefaultAsync<MotivoDevolucao>(new CommandDefinition(
            "SELECT Id, Descricao, Ativo FROM MotivosDevolucao WHERE Descricao = @Descricao",
            new { Descricao = texto },
            cancellationToken: cancellationToken));

        if (existente is not null)
        {
            if (existente.Ativo)
                throw new InvalidOperationException("Este motivo ja esta cadastrado.");

            await connection.ExecuteAsync(new CommandDefinition(
                "UPDATE MotivosDevolucao SET Ativo = TRUE WHERE Id = @Id",
                new { existente.Id },
                cancellationToken: cancellationToken));
            return;
        }

        await connection.ExecuteAsync(new CommandDefinition(
            "INSERT INTO MotivosDevolucao (Descricao, Ativo) VALUES (@Descricao, TRUE)",
            new { Descricao = texto },
            cancellationToken: cancellationToken));
    }

    public async Task DesativarMotivoDevolucaoAsync(
        long id,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await connection.ExecuteAsync(new CommandDefinition(
            "UPDATE MotivosDevolucao SET Ativo = FALSE WHERE Id = @Id",
            new { Id = id },
            cancellationToken: cancellationToken));
    }

    public async Task ConfirmarPreNotaAsync(
        long notaFiscalId,
        IReadOnlyList<DevolucaoItemPreNota> itens,
        CancellationToken cancellationToken = default)
    {
        if (itens.Count == 0)
            throw new InvalidOperationException("Selecione ao menos um produto para devolver.");

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var tx = await connection.BeginTransactionAsync(cancellationToken);

        var statusAtual = await connection.QuerySingleOrDefaultAsync<string>("""
            SELECT StatusConferencia
            FROM NotasFiscais
            WHERE Id = @Id
            """, new { Id = notaFiscalId }, tx);

        if (statusAtual is null)
            throw new InvalidOperationException($"Nota com Id {notaFiscalId} nao encontrada.");

        var devolucaoId = await RegistrarDevolucaoPendenteAsync(connection, tx, notaFiscalId, cancellationToken);

        if (devolucaoId == 0)
        {
            await connection.ExecuteAsync("""
                UPDATE NotasFiscais
                SET StatusConferencia = @Status
                WHERE Id = @Id
                """, new { Id = notaFiscalId, Status = StatusConferenciaValues.Vermelho }, tx);
            await tx.CommitAsync(cancellationToken);
            return;
        }

        var notaDonaId = await connection.QuerySingleAsync<long>(
            "SELECT NotaFiscalId FROM Devolucoes WHERE Id = @Id",
            new { Id = devolucaoId },
            tx);

        await connection.ExecuteAsync("""
            UPDATE NotasFiscais
            SET StatusConferencia = @Status
            WHERE Id = @Id
            """, new
        {
            Id = notaFiscalId,
            Status = notaDonaId == notaFiscalId
                ? StatusConferenciaValues.Vermelho
                : StatusConferenciaValues.Laranja
        }, tx);

        await connection.ExecuteAsync(
            "DELETE FROM DevolucaoItens WHERE DevolucaoId = @DevolucaoId",
            new { DevolucaoId = devolucaoId },
            tx);

        foreach (var item in itens)
        {
            await connection.ExecuteAsync("""
                INSERT INTO DevolucaoItens (
                    DevolucaoId, NotaFiscalId, Sequencia, CodProd, NomeProd,
                    BarrasEan, Quantidade, CustoNota, Motivo, Classe)
                VALUES (
                    @DevolucaoId, @NotaFiscalId, @Sequencia, @CodProd, @NomeProd,
                    @BarrasEan, @Quantidade, @CustoNota, @Motivo, @Classe)
                """,
                new
                {
                    DevolucaoId = devolucaoId,
                    NotaFiscalId = notaFiscalId,
                    item.Sequencia,
                    item.CodProd,
                    item.NomeProd,
                    item.BarrasEan,
                    item.Quantidade,
                    item.CustoNota,
                    item.Motivo,
                    item.Classe
                },
                tx);
        }

        await connection.ExecuteAsync("""
            UPDATE Devolucoes
            SET Andamento = @Andamento
            WHERE Id = @Id
              AND StatusDevolucao = @StatusPendente
            """,
            new
            {
                Id = devolucaoId,
                Andamento = AndamentoDevolucaoValues.AguardandoLoja,
                StatusPendente = StatusDevolucaoValues.Pendente
            },
            tx);

        await tx.CommitAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<DevolucaoItemPreNota>> ObterItensPreNotaAsync(
        long devolucaoId,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhas = await connection.QueryAsync<DevolucaoItemPreNota>(new CommandDefinition(
            """
            SELECT
                Sequencia, CodProd, NomeProd, BarrasEan,
                Quantidade, CustoNota, Motivo, Classe
            FROM DevolucaoItens
            WHERE DevolucaoId = @DevolucaoId
            ORDER BY Sequencia
            """,
            new { DevolucaoId = devolucaoId },
            cancellationToken: cancellationToken));

        return linhas.AsList();
    }

    public async Task<IReadOnlyDictionary<long, IReadOnlyList<DevolucaoItemPreNota>>> ObterItensPreNotaPorDevolucoesAsync(
        IReadOnlyList<long> devolucaoIds,
        CancellationToken cancellationToken = default)
    {
        if (devolucaoIds.Count == 0)
            return new Dictionary<long, IReadOnlyList<DevolucaoItemPreNota>>();

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhas = await connection.QueryAsync<DevolucaoItemLinhaBanco>(new CommandDefinition(
            """
            SELECT
                DevolucaoId, Sequencia, CodProd, NomeProd, BarrasEan,
                Quantidade, CustoNota, Motivo, Classe
            FROM DevolucaoItens
            WHERE DevolucaoId = ANY(@Ids)
            ORDER BY DevolucaoId, Sequencia
            """,
            new { Ids = devolucaoIds.ToArray() },
            cancellationToken: cancellationToken));

        return linhas
            .GroupBy(l => l.DevolucaoId)
            .ToDictionary(
                g => g.Key,
                g => (IReadOnlyList<DevolucaoItemPreNota>)g.Select(l => new DevolucaoItemPreNota
                {
                    Sequencia = l.Sequencia,
                    CodProd = l.CodProd,
                    NomeProd = l.NomeProd,
                    BarrasEan = l.BarrasEan,
                    Quantidade = l.Quantidade,
                    CustoNota = l.CustoNota,
                    Motivo = l.Motivo,
                    Classe = l.Classe
                }).ToList());
    }

    private sealed class DevolucaoItemLinhaBanco
    {
        public long DevolucaoId { get; set; }
        public int Sequencia { get; set; }
        public int CodProd { get; set; }
        public string NomeProd { get; set; } = string.Empty;
        public string BarrasEan { get; set; } = string.Empty;
        public decimal Quantidade { get; set; }
        public decimal CustoNota { get; set; }
        public string Motivo { get; set; } = string.Empty;
        public string Classe { get; set; } = string.Empty;
    }

    public async Task<NotaFiscal?> ObterNotaPorIdAsync(
        long notaFiscalId,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        return await connection.QuerySingleOrDefaultAsync<NotaFiscal>(new CommandDefinition(
            "SELECT * FROM NotasFiscais WHERE Id = @Id",
            new { Id = notaFiscalId },
            cancellationToken: cancellationToken));
    }

    public async Task ConfirmarDevolucaoComItensAsync(
        long devolucaoId,
        long notaFiscalId,
        IReadOnlyList<DevolucaoItemPreNota> itens,
        CancellationToken cancellationToken = default)
    {
        if (itens.Count == 0)
            throw new InvalidOperationException("Confirme ao menos um produto para devolver.");

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var tx = await connection.BeginTransactionAsync(cancellationToken);

        await connection.ExecuteAsync(
            "DELETE FROM DevolucaoItens WHERE DevolucaoId = @DevolucaoId",
            new { DevolucaoId = devolucaoId },
            tx);

        foreach (var item in itens)
        {
            await connection.ExecuteAsync("""
                INSERT INTO DevolucaoItens (
                    DevolucaoId, NotaFiscalId, Sequencia, CodProd, NomeProd,
                    BarrasEan, Quantidade, CustoNota, Motivo, Classe)
                VALUES (
                    @DevolucaoId, @NotaFiscalId, @Sequencia, @CodProd, @NomeProd,
                    @BarrasEan, @Quantidade, @CustoNota, @Motivo, @Classe)
                """,
                new
                {
                    DevolucaoId = devolucaoId,
                    NotaFiscalId = notaFiscalId,
                    item.Sequencia,
                    item.CodProd,
                    item.NomeProd,
                    item.BarrasEan,
                    item.Quantidade,
                    item.CustoNota,
                    item.Motivo,
                    item.Classe
                },
                tx);
        }

        var dataConclusao = DataCompraParser.Formatar(DateTime.Today);
        var linhas = await connection.ExecuteAsync("""
            UPDATE Devolucoes
            SET StatusDevolucao = @StatusDevolucao,
                DataConclusao = @DataConclusao
            WHERE Id = @Id
              AND StatusDevolucao = @StatusPendente
            """,
            new
            {
                Id = devolucaoId,
                StatusDevolucao = StatusDevolucaoValues.Devolvida,
                StatusPendente = StatusDevolucaoValues.Pendente,
                DataConclusao = dataConclusao
            },
            tx);

        if (linhas == 0)
            throw new InvalidOperationException("Esta devolucao ja foi concluida ou nao esta pendente.");

        await tx.CommitAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<DevolucaoObservacao>> ObterObservacoesDevolucaoAsync(
        long devolucaoId,
        CancellationToken cancellationToken = default)
    {
        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);

        var linhas = await connection.QueryAsync<DevolucaoObservacao>(new CommandDefinition(
            """
            SELECT Id, DevolucaoId, Texto, CriadaEm
            FROM DevolucaoObservacoes
            WHERE DevolucaoId = @DevolucaoId
            ORDER BY Id
            """,
            new { DevolucaoId = devolucaoId },
            cancellationToken: cancellationToken));

        return linhas.AsList();
    }

    public async Task AdicionarObservacaoDevolucaoAsync(
        long devolucaoId,
        string texto,
        CancellationToken cancellationToken = default)
    {
        var recado = (texto ?? string.Empty).Trim();
        if (recado.Length == 0)
            throw new ArgumentException("Informe um recado para salvar.", nameof(texto));

        await using var connection = CriarConexao();
        await connection.OpenAsync(cancellationToken);
        await using var tx = await connection.BeginTransactionAsync(cancellationToken);

        var ultima = await connection.QuerySingleOrDefaultAsync<string>("""
            SELECT Texto
            FROM DevolucaoObservacoes
            WHERE DevolucaoId = @DevolucaoId
            ORDER BY Id DESC
            LIMIT 1
            """, new { DevolucaoId = devolucaoId }, tx);

        if (string.Equals(ultima?.Trim(), recado, StringComparison.Ordinal))
        {
            await tx.CommitAsync(cancellationToken);
            return;
        }

        await connection.ExecuteAsync("""
            INSERT INTO DevolucaoObservacoes (DevolucaoId, Texto, CriadaEm)
            VALUES (@DevolucaoId, @Texto, @CriadaEm)
            """,
            new
            {
                DevolucaoId = devolucaoId,
                Texto = recado,
                CriadaEm = DevolucaoObservacaoHistorico.FormatarData(DateTime.Now)
            },
            tx);

        var historico = (await connection.QueryAsync<DevolucaoObservacao>("""
            SELECT Id, DevolucaoId, Texto, CriadaEm
            FROM DevolucaoObservacoes
            WHERE DevolucaoId = @DevolucaoId
            ORDER BY Id
            """, new { DevolucaoId = devolucaoId }, tx)).AsList();

        await connection.ExecuteAsync("""
            UPDATE Devolucoes
            SET Observacao = @Observacao
            WHERE Id = @Id
            """,
            new
            {
                Id = devolucaoId,
                Observacao = DevolucaoObservacaoHistorico.Juntar(historico)
            },
            tx);

        await tx.CommitAsync(cancellationToken);
    }
}
